### PR TITLE
Update tic.R template

### PR DESCRIPTION
**Pull request by pat-s**
#81

### CODE REVIEW

**Comment by krlmlr** [comment]
Deploy preview for *wonderful-volhard-261e08* ready!

Built with commit b073f1ca05716230775fbb27a39a00053f2abe98

https://deploy-preview-82--wonderful-volhard-261e08.netlify.com

**Comment by krlmlr** [comment]
I don't mind building the pkgdown website unconditionally. This would allow detect failures in the build process early, even for pull requests. What are the advantages of turning this off, besides the CPU cycles saved?

**Comment by pat-s** [comment]
I think its confusing for the user to 

1. Build the pkgdown site but don't deploy it eventually
2. Have stage "deploy" two times in the default template (once even before stage "before_deploy"). Users who do not know that the order of stages in `tic.R` does not matter will be confused.

**Comment by pat-s** [comment]
> What are the advantages of turning this off, besides the CPU cycles saved?

In addition, it is time consuming for mid-large size projects.
I think as a default option it should be turned off.

How about shipping multiple "use-ready" commented examples in the template file which users can just uncomment to apply?

**Comment by pat-s** [comment]
Okay, the template changes should go into _travis_ anyway, so maybe we can update the  `tic.R` file of _tic_ after we decided on a new template.

**Comment by pat-s** [comment]
ok, :man_facepalming: 	
I did not see that the actual default in https://github.com/ropenscilabs/travis/blob/master/inst/templates/package/tic.R is to  not build it by default and this setting here is just the custom one for _tic_.

So basically everything written in this thread should not be taken seriously...

**Pull request closed without merging**
