### PR TITLE
Correct links to articles

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by krlmlr** [comment]
Deploy preview for *wonderful-volhard-261e08* ready!

Built with commit 5168d8918533974231134a96149be21ad530457c

https://deploy-preview-93--wonderful-volhard-261e08.netlify.com

**Comment by maelle** [comment]
@pat-s are you a bot like @krlmlr in the message above? super fast merging :wink:

**Comment by pat-s** [comment]
:laughing: looks like it (did not even see the time). Thanks! We hopefully have it CRAN ready soon.

**Comment by maelle** [comment]
I'm reading the advanced article right now, awesome stuff, both the functionalities and the docs themselves!!

**Pull request merged**
