### PR TITLE
Rename pkgname from tic to rci

### LINKED ISSUE #72: Name of the package?
Stupid question maybe, but why is the package named `tic`? Wouldn't something like `ciR` or `ci` be a much more natural name for the package?

### PR DESCRIPTION
**Pull request by pat-s**
Closes #72.

### CODE REVIEW

**Comment by krlmlr** [comment]
Deploy preview for *wonderful-volhard-261e08* ready!

Built with commit 826122edcfa4a38709ff2380900a6d6ba092c2bb

https://deploy-preview-143--wonderful-volhard-261e08.netlify.com

**Comment by krlmlr** [comment]
What a nightmare. Are you really sure we need to rename at this stage?

CC @karthik @maelle.

**Comment by pat-s** [comment]
This was so far just a work of 5 mins using `sed -i /s/tic/rci/g` and adjusting some words that were affected due to the regex clause. Don't think that it will be a major pain.

**Comment by maelle** [comment]
I have no opinion regarding names and technically only know of [this post](https://www.njtierney.com/post/2017/10/27/change-pkg-name/) :-)

**Comment by pat-s** [comment]
Build passing.

The appveyor checks came in by accident when we activated Appveyor checks for all tic.* test packages. To get rid of the App integration here you can either manually remove the app from the repo again or we simply add an `appveyor.yml` file to the repo which omits deployment?

**Comment by karthik** [comment]
Sorry, was there a question concern about changing this from tic to rci?

**Comment by krlmlr** [comment]
Yes. I don't mind renaming if we all agree that

1. "rci" is orders of magnitude better than "tic", and
2. that we don't mind breaking all existing installation that already use {tic}.

For myself, I'm hesitant about breaking (but might be overly cautious), and I don't have a strong opinion regarding the name (I'm biased too).

**Comment by maelle** [comment]
> that we don't mind breaking all existing installation that already use {tic}.

Right. Could you make a GitHub search to get an idea of the scope?

**Comment by krlmlr** [comment]
400-something installations, perhaps with some false positives: https://github.com/search?l=&p=4&q=filename%3Atic.R&type=Code .

Bottom line: if we do it, we need to do it now, but we'd better be sure. Also, a conversion helper for existing repos could ease the transition a lot.

**Comment by maelle** [comment]
> Also, a conversion helper for existing repos could ease the transition a lot.

Or even something helping us making PRs to these repos, although one cannot really do automatic PRs IIRC (without being flagged as bot and banned).

**Comment by pat-s** [comment]
> if we do it, we need to do it now, but we'd better be sure.

+1

The fact that we are not on CRAN and haven't promoted the package yet gives us the legitimation to say that "major things will change" during development, which could include the package name.

From a user perspective, the only thing that needs to be change manually would be `tic.R` -> `rci.R` and the contents of the respective YAML files. I guess both takes < 1 min per repo as a simple "replace all" should do the job.

In my subjectiv world, I like `rci` a lot more. `tic` reminds me all the time of https://en.wikipedia.org/wiki/Tick.

**Comment by krlmlr** [comment]
Let's do it just before Easter then. A simple unexported conversion helper would be useful, still -- even if it's "only" `. %>% readLines() %>% gsub() %>% writeLines()` .

**Comment by pat-s** [comment]
So let's do it?

**Comment by pat-s** [comment]
@krlmlr Each time we commit to master, this PR becomes outdated. So we should agree when exactly we're going to do this and merge right away then.

Conversion is not much of a problem using `sed` but I do not want to do it 12 times :smile:

**Comment by krlmlr** [comment]
We never had a situation with no open pull requests and no pending work in the recent past. Easter was a bit optimistic, but we need to stabilize first before renaming, even if the rename is semi-automatic.

We also need a code that converts existing repos:

- Rename `tic.R` to `rci.R`
- Update `.travis.yml` and `appveyor.yml`
- Change `add_package_checks()` to `do_package_checks()`

Also, if we start with a fresh repo, existing users can continue to use {tic} and migrate at their own pace. This would solve my biggest concern.

I'm closing this for now. Can you automate the rename, so that we're free in our naming choice? That script should create a pristine repo with the code import under the new name as a single commit.

**Pull request closed without merging**
