### PR TITLE
Change default for repo arg of `step_install_deps()`

### LINKED ISSUE #101: Auto-detect Bioconductor pkgs
To ensure deps are properly detected and installed.

`BiocManager::available()` lists all Bioconductor pkgs. 
We could do a diff of all required deps and then optionally call `BiocManager::install()`.

In addition, we should add a `step_install_bioconductor()` step similar to `step_install_cran()`.

### PR DESCRIPTION
**Pull request by pat-s**
So that we support Bioconductor OOB. 

Fixes #101

### CODE REVIEW

**Comment by krlmlr** [comment]
Deploy preview for *wonderful-volhard-261e08* ready!

Built with commit 767ea2c98ac3e20d9f6fb550e82e01f3ef5abf4b

https://deploy-preview-140--wonderful-volhard-261e08.netlify.com

**Comment by krlmlr** [comment]
I'm hesitant to make this the default, also I don't see a way to override it.

Can we instead make it easy to pull in Bioconductor repos, perhaps with functions `tic::repo_cran()` and `tic::repo_bioc()` ? The former would be the default, the latter provides an easy way to specify Bioconductor repos.

**Comment by pat-s** [comment]
> also I don't see a way to override it.

The user can just change the repo argument and it will be populated down?

> Can we instead make it easy to pull in Bioconductor repos, perhaps with functions tic::repo_cran() and tic::repo_bioc() ? 

Functioning only as a wrapper to the command above? That feels overplayed for me here. 

Maybe I do not fully understand the problem of setting this as the default here. Can you give me a heads-up on this?

**Comment by krlmlr** [comment]
I see the override now.

I'd rather use a conservative default. What happens if this method to access Bioconductor chokes or breaks?

The default will be listed in the "Usage" section, it's not particularly nice to look at.

Do we need to override the argument for the macro too?

**Comment by pat-s** [comment]
> I'd rather use a conservative default. What happens if this method to access Bioconductor chokes or breaks?

Then it is our responsibility to update it.

> The default will be listed in the "Usage" section, it's not particularly nice to look at.

I agree. But still, a wrapper just for this 2L chr vec?

> Do we need to override the argument for the macro too?

Yes. That's how I initially got to it because my macro became so cluttered.

**Comment by krlmlr** [comment]
If we don't make this the default, any such problem will hit way fewer people.

I think a wrapper that makes user-facing code easier to read is worth it, even if it's that simple.

To me it looks like the macro has its own `repos` argument:

https://github.com/ropenscilabs/tic/blob/master/R/dsl.R#L115-L127

**Comment by krlmlr** [comment]
Working on a `repo_*()` family of functions that will provide more flexibility and convenience.

**Pull request closed without merging**
