### PR TITLE
Draft for new 'Get started' vignette

### LINKED ISSUE #57: "Get started" vignette
Write from scratch, starting from a mental model of a user who knows what CI is.

See the pull request for a rough structure, feel free to edit.

The new README can be a condensed version of the "Getting started" vignette.

### PR DESCRIPTION
**Pull request by krlmlr**
Addresses #57, not fully ready yet but merging anyway.

### CODE REVIEW

**Comment by maelle** [comment]
Do you deploy the pkgdown website yourself, not by Travis? 😮

**Comment by krlmlr** [comment]
Thanks for the pointer, I'll take a look.

668a4bfd7362e7ea9c7d9cfdb94a9151ea5274d8 happened automatically, but to preview it we'd need Netlify. I can't add this repo to Netlify, who could give Netlify the necessary permissions?

**Comment by maelle** [comment]
Ah that'd be so cool, I was wishing it'd include a preview.

Not sure, not me at least, will ask.

**Comment by krlmlr** [comment]
Merging now, let's continue discussion in #78.

**Pull request merged**
